### PR TITLE
Fix Pulling Down from Artifactory

### PR DESCRIPTION
**Pull request by afiune**
Fixing issue https://github.com/opscode-cookbooks/delivery-cluster/issues/103

### CODE REVIEW

**Comment by tduffield** [comment]
So rather than doing this I think we need to fix how we create deliv_version. According to @schisamo, when we stopped appending the timestamp Artifactory changed how it treated our builds. As such we need to modify the `client.artifact_latest_version` [here](https://github.com/opscode-cookbooks/delivery-cluster/blob/e83a9d767fc17e2d140bb323353e39afad4d219a/libraries/artifactory_helper.rb#L60-L65). 

Essentially the tags now match the versions exactly so it should be something like this: 

```ruby
deliv_version = version || client.artifact_latest_version(
   repos: artifactory_omnibus_repo,
   group: 'com.getchef',
   name: 'delivery'
)
```

You can see what was done here: https://github.com/chef/delivery/blob/d6de3c7b5a010c221cb9229db31bd952e75bd7ef/cookbooks/delivery-dev/recipes/delivery.rb#L27-L38

**Comment by afiune** [comment]
@tduffield but how can we specify a different version other than `latest`?

**Comment by afiune** [comment]
Oh I see what is going on.. But I guess we will loose the flexibility to install delivery versions older than `0.3.0`.. Anyway.. Thanks for that @tduffield .. fixing now

**Comment by jonsmorrow** [comment]
In this case I could go either way on the conditional. I agree with @tduffield in general it is much better to avoid negative conditionals. It makes reading the code optimized for the happy path vrs error conditions.

with this one for a one liner i think the || is more readable than a turnary. I think the clearest thing might be to put this in a helper function with proper if else end.

**Comment by jonsmorrow** [comment]
One other observation. Should we even be pulling from Artifactory anymore? Would it make more sense to pull from chef/current on package cloud and use the same path most of our customers are using?

That's probably for a different change/pr though./

@afiune @tduffield

**Comment by afiune** [comment]
Artifactory is only available for Chef Employees with VPN. (it is optional) The default behavior is to pull it down from `packagecloud`.. I will modify my code with your recommendations. Thanks!

**Comment by afiune** [comment]
Done! @tduffield @jonsmorrow let me know if you want me to change anything else. Cheers!

**Comment by tduffield** [comment]
Looks good right now. I like @jonsmorrow's point about the packagecloud stuff though.

**Pull request merged**
