### PR TITLE
add provisioning node to .kitchen.ssh.yml

### PR DESCRIPTION
**Pull request by stephenlauck**
Would be nice to provide the recommended provisioning node configuration and add a provisioning node to the .kitchen.ssh.yml to build a provision node if the user does not want to provision from their local workstation.

This node when provisioned with have the following:
Install build-essential on linux or developer tools on mac
Install Git
Install ChefDK
Install 'knife push': chef gem install knife-push
Install Delivery CLI

It will also have a fresh delivery-cluster master check out in /home/vagrant plus the ssh keys to communicate to other vagrant nodes for the delivery-cluster ssh build.

### CODE REVIEW

**Comment by afiune** [comment]
Is it a cookbook dependency really needed for this use case? It couldn't be just a single recipe? I like the idea to have a way to create a provisioning node but I am not so sure about creating this essentially to be use by kitchen/vagrant. I rather want this more generic so people can use it with any provider they want.

**Comment by stephenlauck** [comment]
@afiune I include a cookbook called 'chef-provisioning-node' which can be to configure a provisioning node with any provider. I just include a recipe in the cookbook to demonstrate that it can be used locally with kitchen too. If a user wants to build an AWS node, they would just use the chef-provisioning-node cookbook in it's runlist or the recipe that is included in this PR.

**Comment by afiune** [comment]
Uhmmm .. I am just trying to understand from what you are saying, which makes sense, and what I see on the code.. For example: Why there is `vagrant` everywhere? 

* https://github.com/stephenlauck/delivery-cluster/blob/include_provisioning_node/recipes/provisioning_node.rb#L15-L17
* https://github.com/stephenlauck/delivery-cluster/blob/include_provisioning_node/recipes/provisioning_node.rb#L7-L10
* https://github.com/stephenlauck/chef-provisioning-node/blob/master/recipes/setup_ssh_keys.rb#L3,L4
* https://github.com/stephenlauck/chef-provisioning-node/blob/master/recipes/setup_ssh_keys.rb#L10,L11
* https://github.com/stephenlauck/chef-provisioning-node/blob/master/recipes/setup_ssh_keys.rb#L19-L20

**Comment by afiune** [comment]
Closing this since we are now using Delivery to ship delivery-cluster.. Yey! :smile:

**Pull request closed without merging**
