### PR TITLE
add the chef server's hostname to /etc/hosts, to resolve issues on AWS

### LINKED ISSUE #120: chef-server-ctl reconfigure fails on AWS hosts because node.fqdn is undefined
The nginx service is unable to start because its template depends on node.fqdn:  https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/nginx/nginx.conf.erb#L98

but this is nil because:
```
root@ip-33-33-33-254:~# chef-shell 
loading configuration: none (standalone session)
Session type: standalone
Loading.done.

This is the chef-shell.
 Chef Version: 12.3.0
 http://www.chef.io/
 http://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u!
chef > node.fqdn
NoMethodError: Undefined method or attribute `fqdn' on `node'
	from /opt/chef/embedded/apps/chef/lib/chef/node/attribute.rb:468:in `method_missing'
	from /opt/chef/embedded/apps/chef/lib/chef/node.rb:229:in `method_missing'
	from (irb):1
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:76:in `block in start'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `catch'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `start'
	from /opt/chef/embedded/apps/chef/bin/chef-shell:37:in `<top (required)>'
	from /usr/bin/chef-shell:51:in `load'
	from /usr/bin/chef-shell:51:in `<main>'
chef > `hostname -f`
hostname: Name or service not known
 => "" 
```

In my experience you must set an FQDN before you can reconfigure successfully.

### PR DESCRIPTION
**Pull request by irvingpop**
fixes #120 

cc: @afiune for review

### CODE REVIEW

**Comment by stephenlauck** [comment]
:+1: 

I also like the fix for this in the chef-server cookbook https://github.com/chef-cookbooks/chef-server/blob/master/libraries/helpers.rb

**Comment by afiune** [comment]
:open_mouth: @irvingpop I have a quick question:

If you just add the cookbook into the `metadata.rb` it automatically run? :open_mouth: 

No `include_recipe`? :open_mouth:

**Comment by afiune** [comment]
And one more... Does anybody really tested this? :smile:

**Comment by xenolinguist** [comment]
@afiune The [hostsfile cookbook] (https://github.com/customink-webops/hostsfile) doesn't even have a recipes directory, so include_recipe is definitely not needed.

**Comment by irvingpop** [comment]
hey @afiune, my apologies I should've stated that I definitely did test this and it resolved one of my issues.    There will be more PRs coming from me soon as I try to get the AWS case unblocked and working smoothly.

**Comment by afiune** [comment]
@irvingpop no need for apologize my friend :smile: .. I just think it would be awesome if not only the person that is submitting the PR test the functionality. And the reason why I say this is because there are many components on this cookbook and we might ended breaking something that we don't know yet, or a better example is: "It works on my computer" lol 

Does that make sense?

I love that you are pushing things through!! Keep it up! :+1:

**Pull request merged**
