### PR TITLE
Set right permissions to dbuild cert files on build-nodes

### PR DESCRIPTION
**Pull request by afiune**
Fix for https://github.com/opscode-cookbooks/delivery-cluster/issues/101

### CODE REVIEW

**Comment by afiune** [comment]
(btw) This is running very well.. 

```
  * machine_execute[Chown '/etc/chef/trusted_certs' to 'dbuild' user on [build-node-aws-1]] action run
    - run 'chown -R dbuild /etc/chef/trusted_certs' on build-node-aws-1
  * machine_execute[Chown '/etc/chef/trusted_certs' to 'dbuild' user on [build-node-aws-2]] action run
    - run 'chown -R dbuild /etc/chef/trusted_certs' on build-node-aws-2
  * machine_execute[Chown '/etc/chef/trusted_certs' to 'dbuild' user on [build-node-aws-3]] action run
    - run 'chown -R dbuild /etc/chef/trusted_certs' on build-node-aws-3
```

**Comment by cwebberOps** [comment]
Not a huge fan of this solution, but it will unblock folks and does't seem like it will hurt other things. :+1:

**Comment by jonsmorrow** [comment]
yeah I wonder what else we could do. I think it is worth investing the time into finding something permanent. Merge this then look for something else.

We have taken that perspective that the outer and inner chef runs are distinct and shouldn't cross this feels like a cross. can we copy these certs somewhere like dbuilds home or into the workspace dir and own them there by dbuild then cause chef to use that directory when in client mode?

**Comment by cwebberOps** [comment]
@jonsmorrow @afiune in my adventures with provisioning... there is a copy of the certs in `/var/opt/delivery/workspace/etc/trusted_certs`

**Comment by afiune** [comment]
Closing this to don't confuse people..

**Pull request closed without merging**
