### PR TITLE
fix recursive loop when generating environment files

### PR DESCRIPTION
**Pull request by patrick-wright**
I was getting an error when trying to generate the environment config.  This fixed the issue for me.

### CODE REVIEW

**Comment by afiune** [comment]
@patrick-wright thank you for your fix! :smile: We will get this PR tested and then moved it to delivery since we are shipping the code there. Will keep you posted!

**Comment by afiune** [comment]
@someara is testing this.. Some output of the problem he has: https://gist.github.com/someara/88445b61a8e8efa18d93

**Comment by patrick-wright** [comment]
Is that output created running from master or from this branch?  I was getting that error from master.  I used pry to resolve this.

Try adding
```ruby
require 'pry'
binding.pry
```

before line
```ruby
 env_file << ERB.new(DeliveryEnvironment.template)
    .result(DeliveryEnvironment.new(environment, options).binding)
```

to debug in realtime.

**Comment by afiune** [comment]
@patrick-wright we have merged your PR in delivery. We just need to sync to github! :smile: Thanks again for your work..

**Comment by afiune** [comment]
Merged! https://api.github.com/repos/opscode-cookbooks/delivery-cluster/commits/16d214d1ec4433313b4f70e0e27b5848b3705fb0

**Pull request closed without merging**
